# Site Info
title: ngarciaiii
tagline: 'Blog on learning'
description: blog on learning
baseurl: ""
url: http://ngarciaiii.github.io
logo: '/public/logo.png'

# Site configurations
plugins: [jekyll-paginate]
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

# About/contact
author:
  name: ngarciaiii
  description: <strong>Deaf researcher</strong> <strong>learning</strong>  to be a <strong>programmer</strong> and <strong>developer</strong>
  gravatar: 947a7657a5f0f9ae51b585eb98787696 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/nicolas-garcia-iii
    github:    https://github.com/ngarciaiii
    # facebook:  <hide>
    twitter:   https://twitter.com/NicoGiii

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  About:
    - '/about/'
  Blog:
    - '/blog/'
    #  - { Categories: '/blog/categories/' }
    #  - { Tags: '/blog/tags/' }
  Categories: 
    - '/blog/categories/'
  TAGS:
    - '/blog/tags/'
  RESUME:
    - 'public/img/NG_Resume.pdf'



# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/homepage.png
  caption:

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'ngarciaiii-github-io' # leave blank if you don't want disqus

# Port 4444 for listening on different port
port: 4444